### ISSUE TITLE
Input focus states not working as intended

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2579]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The latest release includes changes for all inputs to have a visual 2px primary blue border on focus. However is it not rendering for most of them.

Demo: 

Time Picker styles are working:
```css
.modus-time-picker .input-container:focus-within {
    box-shadow: 0 0 0 1px var(--modus-input-bottom-line-active-color, #217cbb);
    border-color: var(--modus-input-bottom-line-active-color, #217cbb);
}
```

Text Input styles are NOT working:
```css
.modus-text-input .input-container:focus-within {
    box-shadow: 0 0 0 1px var(--modus-input-border-color, 0.0625rem solid var(--modus-input-bottom-line-active-color, #217cbb));
    border-color: var(--modus-input-border-color, 0.0625rem solid var(--modus-input-bottom-line-active-color, #217cbb));
}
```

### Reduced test cases

Visit: https://coliff.github.io/modus-web-components-example/#text-inputs

Click in text inputs to observe border not displaying correctly.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-angular-components

### What version of npm package are you using ?

latest

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

https://modus-web-components.trimble.com/
