### ISSUE TITLE
SLIDER - No difference in selected and non-selected part of slider 

### ISSUE THREAD

**Issue by anwishaZ** [trimble-oss/modus-web-components#2717]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

In slider we expect the slided part alone to be shown as blue color but the whole slider is shown in blue ,which creates a discrepancy in understanding how much area has been covered by the slider .
![image](https://github.com/user-attachments/assets/e2844ac5-b2f9-4d37-a742-ddb01186f64d)

### Motivation and context

The use case is we need to highlight the part which has been covered by the user ,so selected half should be in blue color and the other unselected half should be in grey 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

TRIMBLE FORESTRY 

### What is your team/division name ?

Central Product development

### Are you willing to contribute ?

None

### Are you using Modus Web Components in production ?

Yes

**Comment by coliff** [comment]
This could be fixed with a little bit of JavaScript. I tested this for Modus Bootstrap. Screenshot:
![image](https://github.com/user-attachments/assets/c86e6c91-1009-420d-b685-271d1b2cee16)

Fix:
```css
.form-range::-moz-range-track{background:linear-gradient(to right, #0063a3 0%, #0063a3 var(--value, 0%), #dee2e6 var(--value, 0%), #dee2e6 100%)}
.form-range::-webkit-slider-runnable-track{background:linear-gradient(to right, #0063a3 0%, #0063a3 var(--value, 0%), #dee2e6 var(--value, 0%), #dee2e6 100%)}
```


```js
      // Getting all the range inputs
      const ranges = document.querySelectorAll("input[type=range]");

      // Adding a listener to every input in order to have a dynamic progress
      for (const range of ranges) {
        range.addEventListener("input", () => {
          const value = ((range.value - range.min) / (range.max - range.min)) * 100;
          range.style.setProperty("--value", `${value}%`);
        });
      }

      document.addEventListener("DOMContentLoaded", () => {
        for (const range of ranges) {
          const value = ((range.value - range.min) / (range.max - range.min)) * 100;
          range.style.setProperty("--value", `${value}%`);
        }
      });
```

**Comment by coliff** [comment]
A less good alternative is to use a simple, native form range with the `accent-color:` CSS to use the correct Modus blue.

Demo:
https://codepen.io/coliff/pen/mdZyzLe

```css
input[type="range"] {
  accent-color: #217cbb;
}
```
