### ISSUE TITLE
Modus Buttons - add caret icon

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#274]
For: https://modus-web-components.netlify.app/?path=/docs/components-dropdown--default#default

![image](https://user-images.githubusercontent.com/1212885/149794724-52fcfb19-82d1-40a8-bc65-826ea3bbd799.png)

REF: https://modus-bootstrap.trimble.com/components/dropdowns/

**Comment by coliff** [comment]
I looked into this but couldn't find a way to get it to work. I'd like to add the following CSS class:

```css
  .dropdown-toggle {
    white-space: nowrap;
  }

  .dropdown-toggle::after {
    display: inline-block;
    margin-left: 0.255em;
    vertical-align: 0.255em;
    content: '';
    border-top: 0.3em solid;
    border-right: 0.3em solid transparent;
    border-bottom: 0;
    border-left: 0.3em solid transparent;
  }

  .dropdown-toggle:empty::after {
    margin-left: 0;
  }
```

And the dropdown button should have the `dropdown-toggle` class. How can we do that?
