### ISSUE TITLE
The Modus Modal component is not mobile friendly

### ISSUE THREAD

**Issue by gallelauren816** [trimble-oss/modus-web-components#529]
**Description of the bug**
When you click on a button that opens a modus modal component on a mobile device, a large portion of the modal's content gets cut off because it is on a smaller screen. 

**To Reproduce**
1. Be on a screen of about 375px in width
2. Click on a button that opens a modal
3. Observe the width of the modal and how some of its contents are cutoff

**Expected behavior**
Whether you are on mobile or desktop, you should be able to see the full contents of the modal. You should be able to click on all of the buttons and complete all actions on the modal, regardless of screen size. 

**Screenshots**
![image](https://user-images.githubusercontent.com/95942407/176481899-e6ee52c4-aa39-4c9c-8df9-4aa2e286be87.png)
in the above screenshot, you can see that the modal is too high up on the page of a mobile device and the right side action buttons are cutoff.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
After testing in dev tools, this seems like it would be a good fix for the CSS: 

```css
.modus-modal .content {
   background-color: rgb(255, 255, 255);
   border: 0.0625rem solid rgb(136, 136, 136);
   display: flex;
   flex-direction: column;
   justify-content: center;
   margin: 25% auto;
   max-width: 650px;
   padding: 0px 1rem;
}
```

What was changed in the above CSS: 
* min-width: 375 was removed
* width: max-content was removed
* margin: 15% auto was changed to margin: 25% auto
