### ISSUE TITLE
Add Netlify config

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#548]
The Netlify deploy previews aren't working because we removed the `netlify.toml` config a while ago. It'd be good to get it added back.

**Comment by coliff** [comment]
config to use:

```toml

[build]
  command = "npm run full"
  functions = "netlify/functions"
  publish = "storybook/dist/"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Permissions-Policy = "microphone=()"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    accessibility = 0.8
    best-practices = 0.8
    seo = 0.8
```
