### ISSUE TITLE
CSS Custom Properties in Modus Web components

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#624]
Currently, Modus Web components doesn't provide a way to customize styling for its components because it uses shadow DOM mode, and the code inside shadow DOM is encapsulated which cannot be styled from outside. 
So we need custom properties that can penetrate the shadow DOM.

@ryan-henness-trimble @jeffdoolittle @coliff please correct me if am wrong.

**Comment by ryan-henness-trimble** [comment]
What are some use cases for custom CSS?

**Comment by coliff** [comment]
> What are some use cases for custom CSS? My first thought is that we should try to provide everything the dev may need through the component API

One of the main reasons why using CSS Custom Properties would be helpful is for the adoption of dark mode theme, but also if we could share the common variables between all frameworks then it could help keeping them in sync easier to maintain.

I envision we'd have root variables for the main ones:

```scss
:root {
  --modus-blue: #0063a3; // $col_trimble_blue
  --modus-red: #b44e2a; // $col_trimble_red
  --modus-yellow: #fbad26; // $col_trimble_yellow
  --modus-green: #349c44; // $col_trimble_green
  --modus-white: #fff;
  --modus-gray: #6a6e79; // $col_gray_6
  --modus-gray-dark: #171c1e; // $col_gray_10
  --modus-gray-100: #eaeaef; // $col_gray_0
  --modus-gray-200: #cbcdd6; // $col_gray_1
  --modus-gray-300: #e2e2e7; // $col_gray_2
  --modus-gray-400: #a3a6b1; // $col_gray_3
  --modus-gray-500: #90939f; // $col_gray_4
  --modus-gray-600: #7d808d; // $col_gray_5
  --modus-gray-700: #585c65; // $col_gray_7
  --modus-gray-800: #464b52; // $col_gray_8
  --modus-gray-900: #343a40; // $col_gray_9
  --modus-primary: #0063a3; // $col_trimble_blue
  --modus-secondary: #6a6e79; // $col_gray_6
  --modus-success: #349c44; // $col_trimble_green
  --modus-info: #217cbb; // $col_blue_light
  --modus-warning: #fbad26; // $col_yellow
  --modus-danger: #da212c; // $col_red
  --modus-light: #f1f1f6; // $col_gray_light
  --modus-dark: #171c1e; // $col_gray_10
  --modus-primary-rgb: 0, 99, 163;
  --modus-secondary-rgb: 108, 117, 125;
  --modus-success-rgb: 52, 156, 68;
  --modus-info-rgb: 33, 124, 187;
  --modus-warning-rgb: 251, 173, 38;
  --modus-danger-rgb: 218, 33, 44;
  --modus-light-rgb: 241, 241, 246;
  --modus-dark-rgb: 23, 28, 30;
  --modus-white-rgb: 255, 255, 255;
  --modus-black-rgb: 0, 0, 0;
  --modus-body-color-rgb: 37, 42, 46;
  --modus-body-bg-rgb: 255, 255, 255;
  --modus-font-sans-serif: "Open Sans", system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji",
    "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  --modus-font-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  --modus-gradient: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0));
  --modus-body-font-family: var(--bs-font-sans-serif);
  --modus-body-font-size: 1rem;
  --modus-body-font-weight: 400;
  --modus-body-line-height: 1.5;
  --modus-body-color: #252a2e; //$col_trimble_gray
  --modus-body-bg: #fff;
  --modus-border-width: 1px;
  --modus-border-style: solid;
  --modus-border-color: #90939f; // $col_gray_4
  --modus-border-color-translucent: rgba(0, 0, 0, 0.175);
  --modus-border-radius: 0.125rem;
  --modus-border-radius-sm: 0.125rem;
  --modus-border-radius-lg: 0.25rem;
  --modus-border-radius-xl: 0.5rem;
  --modus-border-radius-2xl: 1rem;
  --modus-border-radius-pill: 50rem;
  --modus-heading-color: ;
  --modus-link-color: #217cbb; // $col_blue_light
  --modus-link-hover-color: #0063a3; // $col_trimble_blue
  --modus-code-color: #d63384;
  --modus-highlight-bg: #fff5e4; // $col_yellow_pale
}
```

And each component would have additional variables e.g.

```scss
.accordion {
  --modus-accordion-color: #000;
  --modus-accordion-bg: #fff;
  --modus-accordion-transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out, border-radius 0.15s ease;
  --modus-accordion-border-color: var(--bs-border-color);
  --modus-accordion-border-width: 0;
  --modus-accordion-border-radius: 0.125rem;
  --modus-accordion-inner-border-radius: 0.125rem;
  --modus-accordion-btn-padding-x: 0.25rem;
  --modus-accordion-btn-padding-y: 0.875rem;
  --modus-accordion-btn-color: #252a2e;
  --modus-accordion-btn-bg: transparent;
  --modus-accordion-btn-icon: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%236a6e79'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
  --modus-accordion-btn-icon-width: 1.25rem;
  --modus-accordion-btn-icon-transform: rotate(-180deg);
  --modus-accordion-btn-icon-transition: transform 0.2s ease-in-out;
  --modus-accordion-btn-active-icon: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%236a6e79'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
  --modus-accordion-btn-focus-border-color: #e0e1e9;
  --modus-accordion-btn-focus-box-shadow: 0 0 0 0.25rem rgba(33, 124, 187, 0.25);
  --modus-accordion-body-padding-x: 1rem;
  --modus-accordion-body-padding-y: 1rem;
  --modus-accordion-active-color: #6a6e79;
  --modus-accordion-active-bg: var(--bs-accordion-bg);
}
```
