### ISSUE TITLE
Modus Accordions should have transition animations

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#690]
See Modus Bootstrap's accordions:
https://modus-bootstrap.trimble.com/components/accordions/#examples

It should be relatively straight-forward to add by just adding some CSS

**Comment by coliff** [comment]
For this we should add this CSS:

```css
.collapse:not(.show) {
  display: none;
}
.collapsing {
  position: relative;
  height: 0;
  overflow: hidden;
  transition: height 0.35s ease;
}
@media (prefers-reduced-motion: reduce) {
  .collapsing {
    transition: none;
  }
}
.collapsing.width {
  width: 0;
  height: auto;
  transition: width 0.35s ease;
}
@media (prefers-reduced-motion: reduce) {
  .collapsing.width {
    transition: none;
  }
}
```

Then when you click on accordion header it should add the `collapsing` class to animate.
